services:
  api:
    container_name: devkor-club-api
    restart: always
    image: node:20.11.0
    command: bash -c "yarn install && yarn start"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3071:3071"
